#!/usr/bin/env python3

import os
import ffmpeg
import argparse
import logging


parser = argparse.ArgumentParser()
parser.add_argument("infile")
args = parser.parse_args()
print(args.infile)

probe = ffmpeg.probe(args.infile)

print(probe)

